### ISSUE TITLE
Task List

### ISSUE THREAD

**Issue by tmpfs** [tmpfs/mana#10]
Development:

* [ ] Integrate contact form - sendgrid account
* [ ] Gallery of photos
* [ ] Booking button on villa pages
* [x] Correct URLs for social links in footer
* [X] Configure CDN
* [ ] Design promo code styling for home page
* [ ] Integrate new copy for Sari villa
* [ ] Integrate updated names when available
* [x] Google analytics integration
* [X] Deploy to amazon
* [x] Update email address on contact page once info@manaveda.com is configured
* [ ] Optimize slideshow images - too big for lower powered mobile devices

Business:

* [ ] Decide on all final names for Penestanan villa
* [ ] Write copy for Sari villa
* [ ] Create booking button account for Penestanan villa and provide link
* [x] Create accounts and provide links for social accounts in footer
* [ ] Supply content for ubud guide page
* [x] Configure info@manaveda.com email address

**Comment by tmpfs** [comment]
Nadia's feedback is that the footer links are not clear and we should consider different names instead of `about|info|contact`.

**Comment by tmpfs** [comment]
Feedback from Shanti includes:

* Different styling for the *Book a Villa* button (does not like the knockout style)
*

**Comment by tmpfs** [comment]
Rename Zen - Mana Boutique

**Comment by tmpfs** [comment]
Replaced by separate issues.
