### ISSUE TITLE
Development Task List

### ISSUE THREAD

**Issue by tmpfs** [tmpfs/mana#11]
* [x] Integrate contact form
* [x] Gallery of photos
* [x] Integrate new copy for Sari villa
* [x] Optimize slideshow images - too big for lower powered mobile devices
* [x] Reduce number of slideshow images
* [x] Deploy contact form server to amazon
* [x] Crop banner images - save a few bytes
* [x] Complete contact form error handling/messaging

---

If siteminder are able to address their issues we need to:

* [x] Add booking button to villa pages
* [ ] Improve styling of booking button
* [ ] Improve visibility of booking button - consider adding to every heading on property pages
* [ ] Design promo code styling for booking page
