### ISSUE TITLE
Business Task List

### ISSUE THREAD

**Issue by tmpfs** [tmpfs/mana#12]
* [x] Create booking button account for boutique villa and provide link
* [ ] Supply content for ubud guide page (text and images)
* [ ] Provide updated content where applicable (our style/the experience etc)
* [ ] Supply logo as 256x256 pixel png or svg image compatible with white and black backgrounds
* [ ] Update copy for Sari villa on Airbnb to avoid duplicate content
* [ ] Decide on all final names for boutique villa rooms (chi, prana) etc
* [ ] Provide updated images for page banners where applicable
* [x] ~Contact siteminder about calendar overlay issue~ (Letter sent to siteminder)
