### ISSUE TITLE
Siteminder Task List

### ISSUE THREAD

**Issue by tmpfs** [tmpfs/mana#14]
If siteminder are able to address their issues we need to:

* [x] Add booking button to villa pages
* [ ] Improve styling of booking button
* [ ] Improve visibility of booking button - consider adding to every heading on property pages
* [ ] Design promo code styling for booking page

**Comment by tmpfs** [comment]
Merged into #11.
